[storage]
[storage.mongo]

url = "mongodb://raven:raven@mongo:27017"
database = "raven"

[storage.redis]
url = "redis://:raven@redis:6379/0"

[plugins]
[plugins.raven_hass_plugin]
hass_instance = "https://hass.dax.gay"
hass_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzY2NkZjU2ZWRkZDY0YTAxYWUyNDAxM2Y4MzFmNWU1YiIsImlhdCI6MTcxOTUxNTg0OCwiZXhwIjoyMDM0ODc1ODQ4fQ._VpOAWYitulf9w04P6h8-c-3B9v5mpeZquukCd71a7U"

[logging]
level = "INFO"